import inspect
import re
import idc
import ida_idaapi
import idaapi
import ida_ida
import ida_bytes
import idaapi
from idc import *

from execfile import execfile, unload, _import
# execfile('di', globals())

# from slowtrace_helpers import eax, get_ea_by_any

def get_itype_string(itype):
    nnol = ['NN_null', 'NN_aaa', 'NN_aad', 'NN_aam', 'NN_aas', 'NN_adc',
            'NN_add', 'NN_and', 'NN_arpl', 'NN_bound', 'NN_bsf', 'NN_bsr', 'NN_bt',
            'NN_btc', 'NN_btr', 'NN_bts', 'NN_call', 'NN_callfi', 'NN_callni',
            'NN_cbw', 'NN_cwde', 'NN_cdqe', 'NN_clc', 'NN_cld', 'NN_cli', 'NN_clts',
            'NN_cmc', 'NN_cmp', 'NN_cmps', 'NN_cwd', 'NN_cdq', 'NN_cqo', 'NN_daa',
            'NN_das', 'NN_dec', 'NN_div', 'NN_enterw', 'NN_enter', 'NN_enterd',
            'NN_enterq', 'NN_hlt', 'NN_idiv', 'NN_imul', 'NN_in', 'NN_inc', 'NN_ins',
            'NN_int', 'NN_into', 'NN_int3', 'NN_iretw', 'NN_iret', 'NN_iretd',
            'NN_iretq', 'NN_ja', 'NN_jae', 'NN_jb', 'NN_jbe', 'NN_jc', 'NN_jcxz',
            'NN_jecxz', 'NN_jrcxz', 'NN_je', 'NN_jg', 'NN_jge', 'NN_jl', 'NN_jle',
            'NN_jna', 'NN_jnae', 'NN_jnb', 'NN_jnbe', 'NN_jnc', 'NN_jne', 'NN_jng',
            'NN_jnge', 'NN_jnl', 'NN_jnle', 'NN_jno', 'NN_jnp', 'NN_jns', 'NN_jnz',
            'NN_jo', 'NN_jp', 'NN_jpe', 'NN_jpo', 'NN_js', 'NN_jz', 'NN_jmp',
            'NN_jmpfi', 'NN_jmpni', 'NN_jmpshort', 'NN_lahf', 'NN_lar', 'NN_lea',
            'NN_leavew', 'NN_leave', 'NN_leaved', 'NN_leaveq', 'NN_lgdt', 'NN_lidt',
            'NN_lgs', 'NN_lss', 'NN_lds', 'NN_les', 'NN_lfs', 'NN_lldt', 'NN_lmsw',
            'NN_lock', 'NN_lods', 'NN_loopw', 'NN_loop', 'NN_loopd', 'NN_loopq',
            'NN_loopwe', 'NN_loope', 'NN_loopde', 'NN_loopqe', 'NN_loopwne',
            'NN_loopne', 'NN_loopdne', 'NN_loopqne', 'NN_lsl', 'NN_ltr', 'NN_mov',
            'NN_movsp', 'NN_movs', 'NN_movsx', 'NN_movzx', 'NN_mul', 'NN_neg',
            'NN_nop', 'NN_not', 'NN_or', 'NN_out', 'NN_outs', 'NN_pop', 'NN_popaw',
            'NN_popa', 'NN_popad', 'NN_popaq', 'NN_popfw', 'NN_popf', 'NN_popfd',
            'NN_popfq', 'NN_push', 'NN_pushaw', 'NN_pusha', 'NN_pushad', 'NN_pushaq',
            'NN_pushfw', 'NN_pushf', 'NN_pushfd', 'NN_pushfq', 'NN_rcl', 'NN_rcr',
            'NN_rol', 'NN_ror', 'NN_rep', 'NN_repe', 'NN_repne', 'NN_retn', 'NN_retf',
            'NN_sahf', 'NN_sal', 'NN_sar', 'NN_shl', 'NN_shr', 'NN_sbb', 'NN_scas',
            'NN_seta', 'NN_setae', 'NN_setb', 'NN_setbe', 'NN_setc', 'NN_sete',
            'NN_setg', 'NN_setge', 'NN_setl', 'NN_setle', 'NN_setna', 'NN_setnae',
            'NN_setnb', 'NN_setnbe', 'NN_setnc', 'NN_setne', 'NN_setng', 'NN_setnge',
            'NN_setnl', 'NN_setnle', 'NN_setno', 'NN_setnp', 'NN_setns', 'NN_setnz',
            'NN_seto', 'NN_setp', 'NN_setpe', 'NN_setpo', 'NN_sets', 'NN_setz',
            'NN_sgdt', 'NN_sidt', 'NN_shld', 'NN_shrd', 'NN_sldt', 'NN_smsw', 'NN_stc',
            'NN_std', 'NN_sti', 'NN_stos', 'NN_str', 'NN_sub', 'NN_test', 'NN_verr',
            'NN_verw', 'NN_wait', 'NN_xchg', 'NN_xlat', 'NN_xor', 'NN_cmpxchg',
            'NN_bswap', 'NN_xadd', 'NN_invd', 'NN_wbinvd', 'NN_invlpg', 'NN_rdmsr',
            'NN_wrmsr', 'NN_cpuid', 'NN_cmpxchg8b', 'NN_rdtsc', 'NN_rsm', 'NN_cmova',
            'NN_cmovb', 'NN_cmovbe', 'NN_cmovg', 'NN_cmovge', 'NN_cmovl', 'NN_cmovle',
            'NN_cmovnb', 'NN_cmovno', 'NN_cmovnp', 'NN_cmovns', 'NN_cmovnz',
            'NN_cmovo', 'NN_cmovp', 'NN_cmovs', 'NN_cmovz', 'NN_fcmovb', 'NN_fcmove',
            'NN_fcmovbe', 'NN_fcmovu', 'NN_fcmovnb', 'NN_fcmovne', 'NN_fcmovnbe',
            'NN_fcmovnu', 'NN_fcomi', 'NN_fucomi', 'NN_fcomip', 'NN_fucomip',
            'NN_rdpmc', 'NN_fld', 'NN_fst', 'NN_fstp', 'NN_fxch', 'NN_fild', 'NN_fist',
            'NN_fistp', 'NN_fbld', 'NN_fbstp', 'NN_fadd', 'NN_faddp', 'NN_fiadd',
            'NN_fsub', 'NN_fsubp', 'NN_fisub', 'NN_fsubr', 'NN_fsubrp', 'NN_fisubr',
            'NN_fmul', 'NN_fmulp', 'NN_fimul', 'NN_fdiv', 'NN_fdivp', 'NN_fidiv',
            'NN_fdivr', 'NN_fdivrp', 'NN_fidivr', 'NN_fsqrt', 'NN_fscale', 'NN_fprem',
            'NN_frndint', 'NN_fxtract', 'NN_fabs', 'NN_fchs', 'NN_fcom', 'NN_fcomp',
            'NN_fcompp', 'NN_ficom', 'NN_ficomp', 'NN_ftst', 'NN_fxam', 'NN_fptan',
            'NN_fpatan', 'NN_f2xm1', 'NN_fyl2x', 'NN_fyl2xp1', 'NN_fldz', 'NN_fld1',
            'NN_fldpi', 'NN_fldl2t', 'NN_fldl2e', 'NN_fldlg2', 'NN_fldln2', 'NN_finit',
            'NN_fninit', 'NN_fsetpm', 'NN_fldcw', 'NN_fstcw', 'NN_fnstcw', 'NN_fstsw',
            'NN_fnstsw', 'NN_fclex', 'NN_fnclex', 'NN_fstenv', 'NN_fnstenv',
            'NN_fldenv', 'NN_fsave', 'NN_fnsave', 'NN_frstor', 'NN_fincstp',
            'NN_fdecstp', 'NN_ffree', 'NN_fnop', 'NN_feni', 'NN_fneni', 'NN_fdisi',
            'NN_fndisi', 'NN_fprem1', 'NN_fsincos', 'NN_fsin', 'NN_fcos', 'NN_fucom',
            'NN_fucomp', 'NN_fucompp', 'NN_setalc', 'NN_svdc', 'NN_rsdc', 'NN_svldt',
            'NN_rsldt', 'NN_svts', 'NN_rsts', 'NN_icebp', 'NN_loadall', 'NN_emms',
            'NN_movd', 'NN_movq', 'NN_packsswb', 'NN_packssdw', 'NN_packuswb',
            'NN_paddb', 'NN_paddw', 'NN_paddd', 'NN_paddsb', 'NN_paddsw', 'NN_paddusb',
            'NN_paddusw', 'NN_pand', 'NN_pandn', 'NN_pcmpeqb', 'NN_pcmpeqw',
            'NN_pcmpeqd', 'NN_pcmpgtb', 'NN_pcmpgtw', 'NN_pcmpgtd', 'NN_pmaddwd',
            'NN_pmulhw', 'NN_pmullw', 'NN_por', 'NN_psllw', 'NN_pslld', 'NN_psllq',
            'NN_psraw', 'NN_psrad', 'NN_psrlw', 'NN_psrld', 'NN_psrlq', 'NN_psubb',
            'NN_psubw', 'NN_psubd', 'NN_psubsb', 'NN_psubsw', 'NN_psubusb',
            'NN_psubusw', 'NN_punpckhbw', 'NN_punpckhwd', 'NN_punpckhdq',
            'NN_punpcklbw', 'NN_punpcklwd', 'NN_punpckldq', 'NN_pxor', 'NN_fxsave',
            'NN_fxrstor', 'NN_sysenter', 'NN_sysexit', 'NN_pavgusb', 'NN_pfadd',
            'NN_pfsub', 'NN_pfsubr', 'NN_pfacc', 'NN_pfcmpge', 'NN_pfcmpgt',
            'NN_pfcmpeq', 'NN_pfmin', 'NN_pfmax', 'NN_pi2fd', 'NN_pf2id', 'NN_pfrcp',
            'NN_pfrsqrt', 'NN_pfmul', 'NN_pfrcpit1', 'NN_pfrsqit1', 'NN_pfrcpit2',
            'NN_pmulhrw', 'NN_femms', 'NN_prefetch', 'NN_prefetchw', 'NN_addps',
            'NN_addss', 'NN_andnps', 'NN_andps', 'NN_cmpps', 'NN_cmpss', 'NN_comiss',
            'NN_cvtpi2ps', 'NN_cvtps2pi', 'NN_cvtsi2ss', 'NN_cvtss2si', 'NN_cvttps2pi',
            'NN_cvttss2si', 'NN_divps', 'NN_divss', 'NN_ldmxcsr', 'NN_maxps',
            'NN_maxss', 'NN_minps', 'NN_minss', 'NN_movaps', 'NN_movhlps', 'NN_movhps',
            'NN_movlhps', 'NN_movlps', 'NN_movmskps', 'NN_movss', 'NN_movups',
            'NN_mulps', 'NN_mulss', 'NN_orps', 'NN_rcpps', 'NN_rcpss', 'NN_rsqrtps',
            'NN_rsqrtss', 'NN_shufps', 'NN_sqrtps', 'NN_sqrtss', 'NN_stmxcsr',
            'NN_subps', 'NN_subss', 'NN_ucomiss', 'NN_unpckhps', 'NN_unpcklps',
            'NN_xorps', 'NN_pavgb', 'NN_pavgw', 'NN_pextrw', 'NN_pinsrw', 'NN_pmaxsw',
            'NN_pmaxub', 'NN_pminsw', 'NN_pminub', 'NN_pmovmskb', 'NN_pmulhuw',
            'NN_psadbw', 'NN_pshufw', 'NN_maskmovq', 'NN_movntps', 'NN_movntq',
            'NN_prefetcht0', 'NN_prefetcht1', 'NN_prefetcht2', 'NN_prefetchnta',
            'NN_sfence', 'NN_cmpeqps', 'NN_cmpltps', 'NN_cmpleps', 'NN_cmpunordps',
            'NN_cmpneqps', 'NN_cmpnltps', 'NN_cmpnleps', 'NN_cmpordps', 'NN_cmpeqss',
            'NN_cmpltss', 'NN_cmpless', 'NN_cmpunordss', 'NN_cmpneqss', 'NN_cmpnltss',
            'NN_cmpnless', 'NN_cmpordss', 'NN_pf2iw', 'NN_pfnacc', 'NN_pfpnacc',
            'NN_pi2fw', 'NN_pswapd', 'NN_fstp1', 'NN_fcom2', 'NN_fcomp3', 'NN_fxch4',
            'NN_fcomp5', 'NN_ffreep', 'NN_fxch7', 'NN_fstp8', 'NN_fstp9', 'NN_addpd',
            'NN_addsd', 'NN_andnpd', 'NN_andpd', 'NN_clflush', 'NN_cmppd', 'NN_cmpsd',
            'NN_comisd', 'NN_cvtdq2pd', 'NN_cvtdq2ps', 'NN_cvtpd2dq', 'NN_cvtpd2pi',
            'NN_cvtpd2ps', 'NN_cvtpi2pd', 'NN_cvtps2dq', 'NN_cvtps2pd', 'NN_cvtsd2si',
            'NN_cvtsd2ss', 'NN_cvtsi2sd', 'NN_cvtss2sd', 'NN_cvttpd2dq',
            'NN_cvttpd2pi', 'NN_cvttps2dq', 'NN_cvttsd2si', 'NN_divpd', 'NN_divsd',
            'NN_lfence', 'NN_maskmovdqu', 'NN_maxpd', 'NN_maxsd', 'NN_mfence',
            'NN_minpd', 'NN_minsd', 'NN_movapd', 'NN_movdq2q', 'NN_movdqa',
            'NN_movdqu', 'NN_movhpd', 'NN_movlpd', 'NN_movmskpd', 'NN_movntdq',
            'NN_movnti', 'NN_movntpd', 'NN_movq2dq', 'NN_movsd', 'NN_movupd',
            'NN_mulpd', 'NN_mulsd', 'NN_orpd', 'NN_paddq', 'NN_pause', 'NN_pmuludq',
            'NN_pshufd', 'NN_pshufhw', 'NN_pshuflw', 'NN_pslldq', 'NN_psrldq',
            'NN_psubq', 'NN_punpckhqdq', 'NN_punpcklqdq', 'NN_shufpd', 'NN_sqrtpd',
            'NN_sqrtsd', 'NN_subpd', 'NN_subsd', 'NN_ucomisd', 'NN_unpckhpd',
            'NN_unpcklpd', 'NN_xorpd', 'NN_syscall', 'NN_sysret', 'NN_swapgs',
            'NN_movddup', 'NN_movshdup', 'NN_movsldup', 'NN_movsxd', 'NN_cmpxchg16b',
            'NN_addsubpd', 'NN_addsubps', 'NN_haddpd', 'NN_haddps', 'NN_hsubpd',
            'NN_hsubps', 'NN_monitor', 'NN_mwait', 'NN_fisttp', 'NN_lddqu',
            'NN_psignb', 'NN_psignw', 'NN_psignd', 'NN_pshufb', 'NN_pmulhrsw',
            'NN_pmaddubsw', 'NN_phsubsw', 'NN_phaddsw', 'NN_phaddw', 'NN_phaddd',
            'NN_phsubw', 'NN_phsubd', 'NN_palignr', 'NN_pabsb', 'NN_pabsw', 'NN_pabsd',
            'NN_vmcall', 'NN_vmclear', 'NN_vmlaunch', 'NN_vmresume', 'NN_vmptrld',
            'NN_vmptrst', 'NN_vmread', 'NN_vmwrite', 'NN_vmxoff', 'NN_vmxon', 'NN_ud2',
            'NN_rdtscp', 'NN_pfrcpv', 'NN_pfrsqrtv', 'NN_cmpeqpd', 'NN_cmpltpd',
            'NN_cmplepd', 'NN_cmpunordpd', 'NN_cmpneqpd', 'NN_cmpnltpd', 'NN_cmpnlepd',
            'NN_cmpordpd', 'NN_cmpeqsd', 'NN_cmpltsd', 'NN_cmplesd', 'NN_cmpunordsd',
            'NN_cmpneqsd', 'NN_cmpnltsd', 'NN_cmpnlesd', 'NN_cmpordsd', 'NN_blendpd',
            'NN_blendps', 'NN_blendvpd', 'NN_blendvps', 'NN_dppd', 'NN_dpps',
            'NN_extractps', 'NN_insertps', 'NN_movntdqa', 'NN_mpsadbw', 'NN_packusdw',
            'NN_pblendvb', 'NN_pblendw', 'NN_pcmpeqq', 'NN_pextrb', 'NN_pextrd',
            'NN_pextrq', 'NN_phminposuw', 'NN_pinsrb', 'NN_pinsrd', 'NN_pinsrq',
            'NN_pmaxsb', 'NN_pmaxsd', 'NN_pmaxud', 'NN_pmaxuw', 'NN_pminsb',
            'NN_pminsd', 'NN_pminud', 'NN_pminuw', 'NN_pmovsxbw', 'NN_pmovsxbd',
            'NN_pmovsxbq', 'NN_pmovsxwd', 'NN_pmovsxwq', 'NN_pmovsxdq', 'NN_pmovzxbw',
            'NN_pmovzxbd', 'NN_pmovzxbq', 'NN_pmovzxwd', 'NN_pmovzxwq', 'NN_pmovzxdq',
            'NN_pmuldq', 'NN_pmulld', 'NN_ptest', 'NN_roundpd', 'NN_roundps',
            'NN_roundsd', 'NN_roundss', 'NN_crc32', 'NN_pcmpestri', 'NN_pcmpestrm',
            'NN_pcmpistri', 'NN_pcmpistrm', 'NN_pcmpgtq', 'NN_popcnt', 'NN_extrq',
            'NN_insertq', 'NN_movntsd', 'NN_movntss', 'NN_lzcnt', 'NN_xgetbv',
            'NN_xrstor', 'NN_xsave', 'NN_xsetbv', 'NN_getsec', 'NN_clgi', 'NN_invlpga',
            'NN_skinit', 'NN_stgi', 'NN_vmexit', 'NN_vmload', 'NN_vmmcall', 'NN_vmrun',
            'NN_vmsave', 'NN_invept', 'NN_invvpid', 'NN_movbe', 'NN_aesenc',
            'NN_aesenclast', 'NN_aesdec', 'NN_aesdeclast', 'NN_aesimc',
            'NN_aeskeygenassist', 'NN_pclmulqdq', 'NN_retnw', 'NN_retnd', 'NN_retnq',
            'NN_retfw', 'NN_retfd', 'NN_retfq', 'NN_rdrand', 'NN_adcx', 'NN_adox',
            'NN_andn', 'NN_bextr', 'NN_blsi', 'NN_blsmsk', 'NN_blsr', 'NN_bzhi',
            'NN_clac', 'NN_mulx', 'NN_pdep', 'NN_pext', 'NN_rorx', 'NN_sarx',
            'NN_shlx', 'NN_shrx', 'NN_stac', 'NN_tzcnt', 'NN_xsaveopt', 'NN_invpcid',
            'NN_rdseed', 'NN_rdfsbase', 'NN_rdgsbase', 'NN_wrfsbase', 'NN_wrgsbase',
            'NN_vaddpd', 'NN_vaddps', 'NN_vaddsd', 'NN_vaddss', 'NN_vaddsubpd',
            'NN_vaddsubps', 'NN_vaesdec', 'NN_vaesdeclast', 'NN_vaesenc',
            'NN_vaesenclast', 'NN_vaesimc', 'NN_vaeskeygenassist', 'NN_vandnpd',
            'NN_vandnps', 'NN_vandpd', 'NN_vandps', 'NN_vblendpd', 'NN_vblendps',
            'NN_vblendvpd', 'NN_vblendvps', 'NN_vbroadcastf128', 'NN_vbroadcasti128',
            'NN_vbroadcastsd', 'NN_vbroadcastss', 'NN_vcmppd', 'NN_vcmpps',
            'NN_vcmpsd', 'NN_vcmpss', 'NN_vcomisd', 'NN_vcomiss', 'NN_vcvtdq2pd',
            'NN_vcvtdq2ps', 'NN_vcvtpd2dq', 'NN_vcvtpd2ps', 'NN_vcvtph2ps',
            'NN_vcvtps2dq', 'NN_vcvtps2pd', 'NN_vcvtps2ph', 'NN_vcvtsd2si',
            'NN_vcvtsd2ss', 'NN_vcvtsi2sd', 'NN_vcvtsi2ss', 'NN_vcvtss2sd',
            'NN_vcvtss2si', 'NN_vcvttpd2dq', 'NN_vcvttps2dq', 'NN_vcvttsd2si',
            'NN_vcvttss2si', 'NN_vdivpd', 'NN_vdivps', 'NN_vdivsd', 'NN_vdivss',
            'NN_vdppd', 'NN_vdpps', 'NN_vextractf128', 'NN_vextracti128',
            'NN_vextractps', 'NN_vfmadd132pd', 'NN_vfmadd132ps', 'NN_vfmadd132sd',
            'NN_vfmadd132ss', 'NN_vfmadd213pd', 'NN_vfmadd213ps', 'NN_vfmadd213sd',
            'NN_vfmadd213ss', 'NN_vfmadd231pd', 'NN_vfmadd231ps', 'NN_vfmadd231sd',
            'NN_vfmadd231ss', 'NN_vfmaddsub132pd', 'NN_vfmaddsub132ps',
            'NN_vfmaddsub213pd', 'NN_vfmaddsub213ps', 'NN_vfmaddsub231pd',
            'NN_vfmaddsub231ps', 'NN_vfmsub132pd', 'NN_vfmsub132ps', 'NN_vfmsub132sd',
            'NN_vfmsub132ss', 'NN_vfmsub213pd', 'NN_vfmsub213ps', 'NN_vfmsub213sd',
            'NN_vfmsub213ss', 'NN_vfmsub231pd', 'NN_vfmsub231ps', 'NN_vfmsub231sd',
            'NN_vfmsub231ss', 'NN_vfmsubadd132pd', 'NN_vfmsubadd132ps',
            'NN_vfmsubadd213pd', 'NN_vfmsubadd213ps', 'NN_vfmsubadd231pd',
            'NN_vfmsubadd231ps', 'NN_vfnmadd132pd', 'NN_vfnmadd132ps',
            'NN_vfnmadd132sd', 'NN_vfnmadd132ss', 'NN_vfnmadd213pd', 'NN_vfnmadd213ps',
            'NN_vfnmadd213sd', 'NN_vfnmadd213ss', 'NN_vfnmadd231pd', 'NN_vfnmadd231ps',
            'NN_vfnmadd231sd', 'NN_vfnmadd231ss', 'NN_vfnmsub132pd', 'NN_vfnmsub132ps',
            'NN_vfnmsub132sd', 'NN_vfnmsub132ss', 'NN_vfnmsub213pd', 'NN_vfnmsub213ps',
            'NN_vfnmsub213sd', 'NN_vfnmsub213ss', 'NN_vfnmsub231pd', 'NN_vfnmsub231ps',
            'NN_vfnmsub231sd', 'NN_vfnmsub231ss', 'NN_vgatherdps', 'NN_vgatherdpd',
            'NN_vgatherqps', 'NN_vgatherqpd', 'NN_vhaddpd', 'NN_vhaddps', 'NN_vhsubpd',
            'NN_vhsubps', 'NN_vinsertf128', 'NN_vinserti128', 'NN_vinsertps',
            'NN_vlddqu', 'NN_vldmxcsr', 'NN_vmaskmovdqu', 'NN_vmaskmovpd',
            'NN_vmaskmovps', 'NN_vmaxpd', 'NN_vmaxps', 'NN_vmaxsd', 'NN_vmaxss',
            'NN_vminpd', 'NN_vminps', 'NN_vminsd', 'NN_vminss', 'NN_vmovapd',
            'NN_vmovaps', 'NN_vmovd', 'NN_vmovddup', 'NN_vmovdqa', 'NN_vmovdqu',
            'NN_vmovhlps', 'NN_vmovhpd', 'NN_vmovhps', 'NN_vmovlhps', 'NN_vmovlpd',
            'NN_vmovlps', 'NN_vmovmskpd', 'NN_vmovmskps', 'NN_vmovntdq',
            'NN_vmovntdqa', 'NN_vmovntpd', 'NN_vmovntps', 'NN_vmovq', 'NN_vmovsd',
            'NN_vmovshdup', 'NN_vmovsldup', 'NN_vmovss', 'NN_vmovupd', 'NN_vmovups',
            'NN_vmpsadbw', 'NN_vmulpd', 'NN_vmulps', 'NN_vmulsd', 'NN_vmulss',
            'NN_vorpd', 'NN_vorps', 'NN_vpabsb', 'NN_vpabsd', 'NN_vpabsw',
            'NN_vpackssdw', 'NN_vpacksswb', 'NN_vpackusdw', 'NN_vpackuswb',
            'NN_vpaddb', 'NN_vpaddd', 'NN_vpaddq', 'NN_vpaddsb', 'NN_vpaddsw',
            'NN_vpaddusb', 'NN_vpaddusw', 'NN_vpaddw', 'NN_vpalignr', 'NN_vpand',
            'NN_vpandn', 'NN_vpavgb', 'NN_vpavgw', 'NN_vpblendd', 'NN_vpblendvb',
            'NN_vpblendw', 'NN_vpbroadcastb', 'NN_vpbroadcastd', 'NN_vpbroadcastq',
            'NN_vpbroadcastw', 'NN_vpclmulqdq', 'NN_vpcmpeqb', 'NN_vpcmpeqd',
            'NN_vpcmpeqq', 'NN_vpcmpeqw', 'NN_vpcmpestri', 'NN_vpcmpestrm',
            'NN_vpcmpgtb', 'NN_vpcmpgtd', 'NN_vpcmpgtq', 'NN_vpcmpgtw',
            'NN_vpcmpistri', 'NN_vpcmpistrm', 'NN_vperm2f128', 'NN_vperm2i128',
            'NN_vpermd', 'NN_vpermilpd', 'NN_vpermilps', 'NN_vpermpd', 'NN_vpermps',
            'NN_vpermq', 'NN_vpextrb', 'NN_vpextrd', 'NN_vpextrq', 'NN_vpextrw',
            'NN_vpgatherdd', 'NN_vpgatherdq', 'NN_vpgatherqd', 'NN_vpgatherqq',
            'NN_vphaddd', 'NN_vphaddsw', 'NN_vphaddw', 'NN_vphminposuw', 'NN_vphsubd',
            'NN_vphsubsw', 'NN_vphsubw', 'NN_vpinsrb', 'NN_vpinsrd', 'NN_vpinsrq',
            'NN_vpinsrw', 'NN_vpmaddubsw', 'NN_vpmaddwd', 'NN_vpmaskmovd',
            'NN_vpmaskmovq', 'NN_vpmaxsb', 'NN_vpmaxsd', 'NN_vpmaxsw', 'NN_vpmaxub',
            'NN_vpmaxud', 'NN_vpmaxuw', 'NN_vpminsb', 'NN_vpminsd', 'NN_vpminsw',
            'NN_vpminub', 'NN_vpminud', 'NN_vpminuw', 'NN_vpmovmskb', 'NN_vpmovsxbd',
            'NN_vpmovsxbq', 'NN_vpmovsxbw', 'NN_vpmovsxdq', 'NN_vpmovsxwd',
            'NN_vpmovsxwq', 'NN_vpmovzxbd', 'NN_vpmovzxbq', 'NN_vpmovzxbw',
            'NN_vpmovzxdq', 'NN_vpmovzxwd', 'NN_vpmovzxwq', 'NN_vpmuldq',
            'NN_vpmulhrsw', 'NN_vpmulhuw', 'NN_vpmulhw', 'NN_vpmulld', 'NN_vpmullw',
            'NN_vpmuludq', 'NN_vpor', 'NN_vpsadbw', 'NN_vpshufb', 'NN_vpshufd',
            'NN_vpshufhw', 'NN_vpshuflw', 'NN_vpsignb', 'NN_vpsignd', 'NN_vpsignw',
            'NN_vpslld', 'NN_vpslldq', 'NN_vpsllq', 'NN_vpsllvd', 'NN_vpsllvq',
            'NN_vpsllw', 'NN_vpsrad', 'NN_vpsravd', 'NN_vpsraw', 'NN_vpsrld',
            'NN_vpsrldq', 'NN_vpsrlq', 'NN_vpsrlvd', 'NN_vpsrlvq', 'NN_vpsrlw',
            'NN_vpsubb', 'NN_vpsubd', 'NN_vpsubq', 'NN_vpsubsb', 'NN_vpsubsw',
            'NN_vpsubusb', 'NN_vpsubusw', 'NN_vpsubw', 'NN_vptest', 'NN_vpunpckhbw',
            'NN_vpunpckhdq', 'NN_vpunpckhqdq', 'NN_vpunpckhwd', 'NN_vpunpcklbw',
            'NN_vpunpckldq', 'NN_vpunpcklqdq', 'NN_vpunpcklwd', 'NN_vpxor',
            'NN_vrcpps', 'NN_vrcpss', 'NN_vroundpd', 'NN_vroundps', 'NN_vroundsd',
            'NN_vroundss', 'NN_vrsqrtps', 'NN_vrsqrtss', 'NN_vshufpd', 'NN_vshufps',
            'NN_vsqrtpd', 'NN_vsqrtps', 'NN_vsqrtsd', 'NN_vsqrtss', 'NN_vstmxcsr',
            'NN_vsubpd', 'NN_vsubps', 'NN_vsubsd', 'NN_vsubss', 'NN_vtestpd',
            'NN_vtestps', 'NN_vucomisd', 'NN_vucomiss', 'NN_vunpckhpd', 'NN_vunpckhps',
            'NN_vunpcklpd', 'NN_vunpcklps', 'NN_vxorpd', 'NN_vxorps', 'NN_vzeroall',
            'NN_vzeroupper', 'NN_xabort', 'NN_xbegin', 'NN_xend', 'NN_xtest',
            'NN_vmgetinfo', 'NN_vmsetinfo', 'NN_vmdxdsbl', 'NN_vmdxenbl', 'NN_vmcpuid',
            'NN_vmhlt', 'NN_vmsplaf', 'NN_vmpushfd', 'NN_vmpopfd', 'NN_vmcli',
            'NN_vmsti', 'NN_vmiretd', 'NN_vmsgdt', 'NN_vmsidt', 'NN_vmsldt',
            'NN_vmstr', 'NN_vmsdte', 'NN_vpcext', 'NN_vfmaddsubps', 'NN_vfmaddsubpd',
            'NN_vfmsubaddps', 'NN_vfmsubaddpd', 'NN_vfmaddps', 'NN_vfmaddpd',
            'NN_vfmaddss', 'NN_vfmaddsd', 'NN_vfmsubps', 'NN_vfmsubpd', 'NN_vfmsubss',
            'NN_vfmsubsd', 'NN_vfnmaddps', 'NN_vfnmaddpd', 'NN_vfnmaddss',
            'NN_vfnmaddsd', 'NN_vfnmsubps', 'NN_vfnmsubpd', 'NN_vfnmsubss',
            'NN_vfnmsubsd', 'NN_bndmk', 'NN_bndcl', 'NN_bndcu', 'NN_bndcn',
            'NN_bndmov', 'NN_bndldx', 'NN_bndstx', 'NN_xrstors', 'NN_xsavec',
            'NN_xsaves', 'NN_prefetchwt1', 'NN_clflushopt', 'NN_clwb', 'NN_pcommit',
            'NN_rdpkru', 'NN_wrpkru', 'NN_vcmpeqpd', 'NN_vcmpltpd', 'NN_vcmplepd',
            'NN_vcmpunordpd', 'NN_vcmpneqpd', 'NN_vcmpnltpd', 'NN_vcmpnlepd',
            'NN_vcmpordpd', 'NN_vcmpeq_uqpd', 'NN_vcmpngepd', 'NN_vcmpngtpd',
            'NN_vcmpfalsepd', 'NN_vcmpneq_oqpd', 'NN_vcmpgepd', 'NN_vcmpgtpd',
            'NN_vcmptruepd', 'NN_vcmpeq_ospd', 'NN_vcmplt_oqpd', 'NN_vcmple_oqpd',
            'NN_vcmpunord_spd', 'NN_vcmpneq_uspd', 'NN_vcmpnlt_uqpd',
            'NN_vcmpnle_uqpd', 'NN_vcmpord_spd', 'NN_vcmpeq_uspd', 'NN_vcmpnge_uqpd',
            'NN_vcmpngt_uqpd', 'NN_vcmpfalse_ospd', 'NN_vcmpneq_ospd',
            'NN_vcmpge_oqpd', 'NN_vcmpgt_oqpd', 'NN_vcmptrue_uspd', 'NN_vcmpeqps',
            'NN_vcmpltps', 'NN_vcmpleps', 'NN_vcmpunordps', 'NN_vcmpneqps',
            'NN_vcmpnltps', 'NN_vcmpnleps', 'NN_vcmpordps', 'NN_vcmpeq_uqps',
            'NN_vcmpngeps', 'NN_vcmpngtps', 'NN_vcmpfalseps', 'NN_vcmpneq_oqps',
            'NN_vcmpgeps', 'NN_vcmpgtps', 'NN_vcmptrueps', 'NN_vcmpeq_osps',
            'NN_vcmplt_oqps', 'NN_vcmple_oqps', 'NN_vcmpunord_sps', 'NN_vcmpneq_usps',
            'NN_vcmpnlt_uqps', 'NN_vcmpnle_uqps', 'NN_vcmpord_sps', 'NN_vcmpeq_usps',
            'NN_vcmpnge_uqps', 'NN_vcmpngt_uqps', 'NN_vcmpfalse_osps',
            'NN_vcmpneq_osps', 'NN_vcmpge_oqps', 'NN_vcmpgt_oqps', 'NN_vcmptrue_usps',
            'NN_vcmpeqsd', 'NN_vcmpltsd', 'NN_vcmplesd', 'NN_vcmpunordsd',
            'NN_vcmpneqsd', 'NN_vcmpnltsd', 'NN_vcmpnlesd', 'NN_vcmpordsd',
            'NN_vcmpeq_uqsd', 'NN_vcmpngesd', 'NN_vcmpngtsd', 'NN_vcmpfalsesd',
            'NN_vcmpneq_oqsd', 'NN_vcmpgesd', 'NN_vcmpgtsd', 'NN_vcmptruesd',
            'NN_vcmpeq_ossd', 'NN_vcmplt_oqsd', 'NN_vcmple_oqsd', 'NN_vcmpunord_ssd',
            'NN_vcmpneq_ussd', 'NN_vcmpnlt_uqsd', 'NN_vcmpnle_uqsd', 'NN_vcmpord_ssd',
            'NN_vcmpeq_ussd', 'NN_vcmpnge_uqsd', 'NN_vcmpngt_uqsd',
            'NN_vcmpfalse_ossd', 'NN_vcmpneq_ossd', 'NN_vcmpge_oqsd', 'NN_vcmpgt_oqsd',
            'NN_vcmptrue_ussd', 'NN_vcmpeqss', 'NN_vcmpltss', 'NN_vcmpless',
            'NN_vcmpunordss', 'NN_vcmpneqss', 'NN_vcmpnltss', 'NN_vcmpnless',
            'NN_vcmpordss', 'NN_vcmpeq_uqss', 'NN_vcmpngess', 'NN_vcmpngtss',
            'NN_vcmpfalsess', 'NN_vcmpneq_oqss', 'NN_vcmpgess', 'NN_vcmpgtss',
            'NN_vcmptruess', 'NN_vcmpeq_osss', 'NN_vcmplt_oqss', 'NN_vcmple_oqss',
            'NN_vcmpunord_sss', 'NN_vcmpneq_usss', 'NN_vcmpnlt_uqss',
            'NN_vcmpnle_uqss', 'NN_vcmpord_sss', 'NN_vcmpeq_usss', 'NN_vcmpnge_uqss',
            'NN_vcmpngt_uqss', 'NN_vcmpfalse_osss', 'NN_vcmpneq_osss',
            'NN_vcmpge_oqss', 'NN_vcmpgt_oqss', 'NN_vcmptrue_usss', 'NN_valignd',
            'NN_valignq', 'NN_vblendmpd', 'NN_vblendmps', 'NN_vpblendmb',
            'NN_vpblendmw', 'NN_vpblendmd', 'NN_vpblendmq', 'NN_vbroadcastf32x2',
            'NN_vbroadcastf32x4', 'NN_vbroadcastf64x2', 'NN_vbroadcastf32x8',
            'NN_vbroadcastf64x4', 'NN_vbroadcasti32x2', 'NN_vbroadcasti32x4',
            'NN_vbroadcasti64x2', 'NN_vbroadcasti32x8', 'NN_vbroadcasti64x4',
            'NN_vcompresspd', 'NN_vcompressps', 'NN_vcvtpd2qq', 'NN_vcvtpd2udq',
            'NN_vcvtpd2uqq', 'NN_vcvtps2udq', 'NN_vcvtps2qq', 'NN_vcvtps2uqq',
            'NN_vcvtqq2pd', 'NN_vcvtqq2ps', 'NN_vcvtsd2usi', 'NN_vcvtss2usi',
            'NN_vcvttpd2qq', 'NN_vcvttpd2udq', 'NN_vcvttpd2uqq', 'NN_vcvttps2udq',
            'NN_vcvttps2qq', 'NN_vcvttps2uqq', 'NN_vcvttsd2usi', 'NN_vcvttss2usi',
            'NN_vcvtudq2pd', 'NN_vcvtudq2ps', 'NN_vcvtuqq2pd', 'NN_vcvtuqq2ps',
            'NN_vcvtusi2sd', 'NN_vcvtusi2ss', 'NN_vdbpsadbw', 'NN_vexpandpd',
            'NN_vexpandps', 'NN_vextractf32x4', 'NN_vextractf64x2', 'NN_vextractf32x8',
            'NN_vextractf64x4', 'NN_vextracti32x4', 'NN_vextracti64x2',
            'NN_vextracti32x8', 'NN_vextracti64x4', 'NN_vfixupimmpd', 'NN_vfixupimmps',
            'NN_vfixupimmsd', 'NN_vfixupimmss', 'NN_vfpclasspd', 'NN_vfpclassps',
            'NN_vfpclasssd', 'NN_vfpclassss', 'NN_vgetexppd', 'NN_vgetexpps',
            'NN_vgetexpsd', 'NN_vgetexpss', 'NN_vgetmantpd', 'NN_vgetmantps',
            'NN_vgetmantsd', 'NN_vgetmantss', 'NN_vinsertf32x4', 'NN_vinsertf64x2',
            'NN_vinsertf32x8', 'NN_vinsertf64x4', 'NN_vinserti32x4', 'NN_vinserti64x2',
            'NN_vinserti32x8', 'NN_vinserti64x4', 'NN_vmovdqa32', 'NN_vmovdqa64',
            'NN_vmovdqu8', 'NN_vmovdqu16', 'NN_vmovdqu32', 'NN_vmovdqu64', 'NN_vpabsq',
            'NN_vpandd', 'NN_vpandq', 'NN_vpandnd', 'NN_vpandnq', 'NN_vpbroadcastmb2q',
            'NN_vpbroadcastmw2d', 'NN_vpcmpb', 'NN_vpcmpub', 'NN_vpcmpd', 'NN_vpcmpud',
            'NN_vpcmpq', 'NN_vpcmpuq', 'NN_vpcmpw', 'NN_vpcmpuw', 'NN_vpcompressd',
            'NN_vpcompressq', 'NN_vpconflictd', 'NN_vpconflictq', 'NN_vpermb',
            'NN_vpermw', 'NN_vpermi2b', 'NN_vpermi2w', 'NN_vpermi2d', 'NN_vpermi2q',
            'NN_vpermi2ps', 'NN_vpermi2pd', 'NN_vpermt2b', 'NN_vpermt2w',
            'NN_vpermt2d', 'NN_vpermt2q', 'NN_vpermt2ps', 'NN_vpermt2pd',
            'NN_vpexpandd', 'NN_vpexpandq', 'NN_vplzcntd', 'NN_vplzcntq',
            'NN_vpmadd52luq', 'NN_vpmadd52huq', 'NN_vpmaxsq', 'NN_vpmaxuq',
            'NN_vpminsq', 'NN_vpminuq', 'NN_vpmovm2b', 'NN_vpmovm2w', 'NN_vpmovm2d',
            'NN_vpmovm2q', 'NN_vpmovb2m', 'NN_vpmovw2m', 'NN_vpmovd2m', 'NN_vpmovq2m',
            'NN_vpmovqb', 'NN_vpmovsqb', 'NN_vpmovusqb', 'NN_vpmovqw', 'NN_vpmovsqw',
            'NN_vpmovusqw', 'NN_vpmovqd', 'NN_vpmovsqd', 'NN_vpmovusqd', 'NN_vpmovdb',
            'NN_vpmovsdb', 'NN_vpmovusdb', 'NN_vpmovdw', 'NN_vpmovsdw', 'NN_vpmovusdw',
            'NN_vpmovwb', 'NN_vpmovswb', 'NN_vpmovuswb', 'NN_vpmullq',
            'NN_vpmultishiftqb', 'NN_vpord', 'NN_vporq', 'NN_vprold', 'NN_vprolvd',
            'NN_vprolq', 'NN_vprolvq', 'NN_vprord', 'NN_vprorvd', 'NN_vprorq',
            'NN_vprorvq', 'NN_vpscatterdd', 'NN_vpscatterdq', 'NN_vpscatterqd',
            'NN_vpscatterqq', 'NN_vpsraq', 'NN_vpsllvw', 'NN_vpsrlvw', 'NN_vptestnmb',
            'NN_vptestnmw', 'NN_vptestnmd', 'NN_vptestnmq', 'NN_vshuff32x4',
            'NN_vshuff64x2', 'NN_vshufi32x4', 'NN_vshufi64x2', 'NN_vpternlogd',
            'NN_vpternlogq', 'NN_vptestmb', 'NN_vptestmw', 'NN_vptestmd',
            'NN_vptestmq', 'NN_vpsravw', 'NN_vpsravq', 'NN_vpxord', 'NN_vpxorq',
            'NN_vrangepd', 'NN_vrangeps', 'NN_vrangesd', 'NN_vrangess', 'NN_vrcp14pd',
            'NN_vrcp14sd', 'NN_vrcp14ps', 'NN_vrcp14ss', 'NN_vreducepd',
            'NN_vreducesd', 'NN_vreduceps', 'NN_vreducess', 'NN_vrndscalepd',
            'NN_vrndscalesd', 'NN_vrndscaleps', 'NN_vrndscaless', 'NN_vrsqrt14pd',
            'NN_vrsqrt14sd', 'NN_vrsqrt14ps', 'NN_vrsqrt14ss', 'NN_vscalefpd',
            'NN_vscalefsd', 'NN_vscalefps', 'NN_vscalefss', 'NN_vscatterdps',
            'NN_vscatterdpd', 'NN_vscatterqps', 'NN_vscatterqpd', 'NN_vexp2pd',
            'NN_vexp2ps', 'NN_vrcp28pd', 'NN_vrcp28sd', 'NN_vrcp28ps', 'NN_vrcp28ss',
            'NN_vrsqrt28pd', 'NN_vrsqrt28sd', 'NN_vrsqrt28ps', 'NN_vrsqrt28ss',
            'NN_vgatherpf0dps', 'NN_vgatherpf0qps', 'NN_vgatherpf0dpd',
            'NN_vgatherpf0qpd', 'NN_vgatherpf1dps', 'NN_vgatherpf1qps',
            'NN_vgatherpf1dpd', 'NN_vgatherpf1qpd', 'NN_vscatterpf0dps',
            'NN_vscatterpf0qps', 'NN_vscatterpf0dpd', 'NN_vscatterpf0qpd',
            'NN_vscatterpf1dps', 'NN_vscatterpf1qps', 'NN_vscatterpf1dpd',
            'NN_vscatterpf1qpd', 'NN_vpcmpltd', 'NN_vpcmpled', 'NN_vpcmpneqd',
            'NN_vpcmpnltd', 'NN_vpcmpnled', 'NN_vpcmpequd', 'NN_vpcmpltud',
            'NN_vpcmpleud', 'NN_vpcmpnequd', 'NN_vpcmpnltud', 'NN_vpcmpnleud',
            'NN_vpcmpltq', 'NN_vpcmpleq', 'NN_vpcmpneqq', 'NN_vpcmpnltq',
            'NN_vpcmpnleq', 'NN_vpcmpequq', 'NN_vpcmpltuq', 'NN_vpcmpleuq',
            'NN_vpcmpnequq', 'NN_vpcmpnltuq', 'NN_vpcmpnleuq', 'NN_kaddw', 'NN_kaddb',
            'NN_kaddq', 'NN_kaddd', 'NN_kandw', 'NN_kandb', 'NN_kandq', 'NN_kandd',
            'NN_kandnw', 'NN_kandnb', 'NN_kandnq', 'NN_kandnd', 'NN_kmovw', 'NN_kmovb',
            'NN_kmovq', 'NN_kmovd', 'NN_kunpckbw', 'NN_kunpckwd', 'NN_kunpckdq',
            'NN_knotw', 'NN_knotb', 'NN_knotq', 'NN_knotd', 'NN_korw', 'NN_korb',
            'NN_korq', 'NN_kord', 'NN_kortestw', 'NN_kortestb', 'NN_kortestq',
            'NN_kortestd', 'NN_kshiftlw', 'NN_kshiftlb', 'NN_kshiftlq', 'NN_kshiftld',
            'NN_kshiftrw', 'NN_kshiftrb', 'NN_kshiftrq', 'NN_kshiftrd', 'NN_kxnorw',
            'NN_kxnorb', 'NN_kxnorq', 'NN_kxnord', 'NN_ktestw', 'NN_ktestb',
            'NN_ktestq', 'NN_ktestd', 'NN_kxorw', 'NN_kxorb', 'NN_kxorq', 'NN_kxord',
            'NN_sha1rnds4', 'NN_sha1nexte', 'NN_sha1msg1', 'NN_sha1msg2',
            'NN_sha256rnds2', 'NN_sha256msg1', 'NN_sha256msg2', 'NN_encls', 'NN_enclu',
            'NN_vfrczpd', 'NN_vfrczps', 'NN_vfrczsd', 'NN_vfrczss', 'NN_vpcmov',
            'NN_vpcomb', 'NN_vpcomd', 'NN_vpcomq', 'NN_vpcomub', 'NN_vpcomud',
            'NN_vpcomuq', 'NN_vpcomuw', 'NN_vpcomw', 'NN_vpermil2pd', 'NN_vpermil2ps',
            'NN_vphaddbd', 'NN_vphaddbq', 'NN_vphaddbw', 'NN_vphadddq', 'NN_vphaddubd',
            'NN_vphaddubq', 'NN_vphaddubw', 'NN_vphaddudq', 'NN_vphadduwd',
            'NN_vphadduwq', 'NN_vphaddwd', 'NN_vphaddwq', 'NN_vphsubbw', 'NN_vphsubdq',
            'NN_vphsubwd', 'NN_vpmacsdd', 'NN_vpmacsdqh', 'NN_vpmacsdql',
            'NN_vpmacssdd', 'NN_vpmacssdqh', 'NN_vpmacssdql', 'NN_vpmacsswd',
            'NN_vpmacssww', 'NN_vpmacswd', 'NN_vpmacsww', 'NN_vpmadcsswd',
            'NN_vpmadcswd', 'NN_vpperm', 'NN_vprotb', 'NN_vprotd', 'NN_vprotq',
            'NN_vprotw', 'NN_vpshab', 'NN_vpshad', 'NN_vpshaq', 'NN_vpshaw',
            'NN_vpshlb', 'NN_vpshld', 'NN_vpshlq', 'NN_vpshlw', 'NN_vpcomltb',
            'NN_vpcomleb', 'NN_vpcomgtb', 'NN_vpcomgeb', 'NN_vpcomeqb', 'NN_vpcomneqb',
            'NN_vpcomfalseb', 'NN_vpcomtrueb', 'NN_vpcomltw', 'NN_vpcomlew',
            'NN_vpcomgtw', 'NN_vpcomgew', 'NN_vpcomeqw', 'NN_vpcomneqw',
            'NN_vpcomfalsew', 'NN_vpcomtruew', 'NN_vpcomltd', 'NN_vpcomled',
            'NN_vpcomgtd', 'NN_vpcomged', 'NN_vpcomeqd', 'NN_vpcomneqd',
            'NN_vpcomfalsed', 'NN_vpcomtrued', 'NN_vpcomltq', 'NN_vpcomleq',
            'NN_vpcomgtq', 'NN_vpcomgeq', 'NN_vpcomeqq', 'NN_vpcomneqq',
            'NN_vpcomfalseq', 'NN_vpcomtrueq', 'NN_vpcomltub', 'NN_vpcomleub',
            'NN_vpcomgtub', 'NN_vpcomgeub', 'NN_vpcomequb', 'NN_vpcomnequb',
            'NN_vpcomfalseub', 'NN_vpcomtrueub', 'NN_vpcomltuw', 'NN_vpcomleuw',
            'NN_vpcomgtuw', 'NN_vpcomgeuw', 'NN_vpcomequw', 'NN_vpcomnequw',
            'NN_vpcomfalseuw', 'NN_vpcomtrueuw', 'NN_vpcomltud', 'NN_vpcomleud',
            'NN_vpcomgtud', 'NN_vpcomgeud', 'NN_vpcomequd', 'NN_vpcomnequd',
            'NN_vpcomfalseud', 'NN_vpcomtrueud', 'NN_vpcomltuq', 'NN_vpcomleuq',
            'NN_vpcomgtuq', 'NN_vpcomgeuq', 'NN_vpcomequq', 'NN_vpcomnequq',
            'NN_vpcomfalseuq', 'NN_vpcomtrueuq', 'NN_monitorx', 'NN_mwaitx',
            'NN_clzero', 'NN_ptwrite', 'NN_v4fmaddps', 'NN_v4fnmaddps', 'NN_v4fmaddss',
            'NN_v4fnmaddss', 'NN_vp4dpwssd', 'NN_vp4dpwssds', 'NN_vpopcntd',
            'NN_vpopcntq', 'NN_rdpid', 'NN_vmfunc', 'NN_incsspd', 'NN_incsspq',
            'NN_rdsspd', 'NN_rdsspq', 'NN_saveprevssp', 'NN_rstorssp', 'NN_wrssd',
            'NN_wrssq', 'NN_wrussd', 'NN_wrussq', 'NN_setssbsy', 'NN_clrssbsy',
            'NN_endbr64', 'NN_endbr32', 'NN_last']
    return nnol[itype]
